# Dependencies
# markdown:         redcarpet
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Anujraaj Goyal
tagline:          'Roboticist!'
description:      'Thanks for stumbling upon!'
url:              https://goel42.github.io
baseurl:          /

author:
  name:           'Anujraaj Goyal'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/goel42/goel42.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  # - redcarpet